---

- hosts: local
  gather_facts: False

  tasks:

    - import_tasks: tasks/set_vars.yml
    - include_tasks: tasks/create_app_config.yml
      loop: "{{ apps }}"
      loop_control:
        loop_var: app
      when: apps is defined
