---
# Create route aliases

- name: Build a list of all aliases
  set_fact:
    routes_aliases: "{{ routes_aliases }} + [ '{{ item }}']"
  with_items: "{{ openshift_routes_aliases | json_query('[*].aliases') }}"
  when: item is not none and item != ""
  vars:
    routes_aliases: []

- name: Make sure all redirected routes exist or force recreation
  openshift_raw:
    force: true
    definition: "{{ lookup('template', 'apps/redirect/templates/nginx/_route.yml.j2') | from_yaml }}"
    state: present
  with_items: "{{ routes_aliases }}"
  when: routes_aliases is defined
